import type { MathLearningItem } from '../types/math';

export const MATH_LEARNING_ITEMS: MathLearningItem[] = [
    {
        id: 'akila',
        name: '加法練習',
        icon: '➕',
        description: '數學計算挑戰',
        subjectId: 'math',
        stageId: 'elementary',
        domain: 'number_operations',
        grades: ['國小低年級', '國小中年級'],
        supportsVisualAid: false,
        practiceModes: ['basic_arithmetic'],
        order: 1,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'html',
            target: '/games/akila_plus_test.html',
        },
        legacyDisabledKey: 'akila',
        accentColorToken: 'blue',
        tags: ['加法', '四則運算'],
    },
    {
        id: 'subtraction',
        name: '減法練習',
        icon: '➖',
        description: '減法計算挑戰',
        subjectId: 'math',
        stageId: 'elementary',
        domain: 'number_operations',
        grades: ['國小低年級', '國小中年級'],
        supportsVisualAid: false,
        practiceModes: ['basic_arithmetic'],
        order: 2,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'html',
            target: '/games/subtraction_test.html',
        },
        legacyDisabledKey: 'subtraction',
        accentColorToken: 'green',
        tags: ['減法', '四則運算'],
    },
    {
        id: 'multiplication',
        name: '乘法練習',
        icon: '✖️',
        description: '九九乘法表',
        subjectId: 'math',
        stageId: 'elementary',
        domain: 'number_operations',
        grades: ['國小中年級'],
        supportsVisualAid: false,
        practiceModes: ['basic_arithmetic'],
        order: 3,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'html',
            target: '/games/multiplication_test.html',
        },
        legacyDisabledKey: 'multiplication',
        accentColorToken: 'purple',
        tags: ['乘法', '四則運算'],
    },
    {
        id: 'division',
        name: '除法練習',
        icon: '➗',
        description: '除法與餘數',
        subjectId: 'math',
        stageId: 'elementary',
        domain: 'number_operations',
        grades: ['國小中年級', '國小高年級'],
        supportsVisualAid: false,
        practiceModes: ['basic_arithmetic'],
        order: 4,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'html',
            target: '/games/division_test.html',
        },
        legacyDisabledKey: 'division',
        accentColorToken: 'orange',
        tags: ['除法', '餘數', '四則運算'],
    },
    {
        id: 'fractions',
        name: '分數練習',
        shortName: '分數',
        icon: '🍰',
        description: '分數辨識、約分與分數加減',
        subjectId: 'math',
        stageId: 'elementary',
        domain: 'fractions',
        grades: ['國小高年級'],
        supportsVisualAid: true,
        practiceModes: ['fraction_recognition', 'fraction_operations'],
        order: 10,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'react',
            target: 'fractions',
        },
        legacyDisabledKey: 'fractions',
        accentColorToken: 'pink',
        tags: ['分數', '約分', '通分'],
    },
    {
        id: 'factors_multiples',
        name: '因數與倍數',
        shortName: '因倍數',
        icon: '🧩',
        description: '因數、倍數、最大公因數與最小公倍數',
        subjectId: 'math',
        stageId: 'elementary',
        domain: 'factors_multiples',
        grades: ['國小高年級'],
        supportsVisualAid: false,
        practiceModes: ['factor_multiple_rules'],
        order: 11,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'react',
            target: 'factors_multiples',
        },
        legacyDisabledKey: 'factors_multiples',
        accentColorToken: 'cyan',
        tags: ['因數', '倍數', 'gcf', 'lcm'],
    },
    {
        id: 'perimeter',
        name: '周長',
        icon: '📏',
        description: '正方形、長方形與複合圖形周長',
        subjectId: 'math',
        stageId: 'elementary',
        domain: 'geometry',
        grades: ['國小中年級', '國小高年級'],
        supportsVisualAid: true,
        practiceModes: ['perimeter_calculation'],
        order: 12,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'react',
            target: 'perimeter',
        },
        legacyDisabledKey: 'perimeter',
        accentColorToken: 'yellow',
        tags: ['周長', '幾何'],
    },
    {
        id: 'area',
        name: '面積',
        icon: '🟦',
        description: '長方形、正方形、三角形與平行四邊形面積',
        subjectId: 'math',
        stageId: 'elementary',
        domain: 'measurement',
        grades: ['國小中年級', '國小高年級'],
        supportsVisualAid: true,
        practiceModes: ['area_calculation'],
        order: 13,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'react',
            target: 'area',
        },
        legacyDisabledKey: 'area',
        accentColorToken: 'indigo',
        tags: ['面積', '方格圖'],
    },
    {
        id: 'volume',
        name: '體積',
        icon: '🧊',
        description: '正方體與長方體體積',
        subjectId: 'math',
        stageId: 'elementary',
        domain: 'measurement',
        grades: ['國小高年級'],
        supportsVisualAid: true,
        practiceModes: ['volume_calculation'],
        order: 14,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'react',
            target: 'volume',
        },
        legacyDisabledKey: 'volume',
        accentColorToken: 'sky',
        tags: ['體積', '立方體'],
    },
    {
        id: 'linear_equation',
        name: '一元一次方程式',
        shortName: '方程式',
        icon: '🟰',
        description: '一步驟與兩步驟方程式練習',
        subjectId: 'math',
        stageId: 'junior_high',
        domain: 'algebra',
        grades: ['國一'],
        supportsVisualAid: false,
        practiceModes: ['linear_equation_solving'],
        order: 20,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'react',
            target: 'linear_equation',
        },
        legacyDisabledKey: 'linear_equation',
        accentColorToken: 'emerald',
        tags: ['代數', '一元一次方程式'],
    },
    {
        id: 'polynomials',
        name: '多項式基礎',
        shortName: '多項式',
        icon: '📐',
        description: '同類項辨識、合併與代入求值',
        subjectId: 'math',
        stageId: 'junior_high',
        domain: 'algebra',
        grades: ['國一'],
        supportsVisualAid: false,
        practiceModes: ['polynomial_basics'],
        order: 21,
        enabledByDefault: true,
        status: 'active',
        launcher: {
            type: 'react',
            target: 'polynomials',
        },
        legacyDisabledKey: 'polynomials',
        accentColorToken: 'violet',
        tags: ['代數', '多項式'],
    },
];
